### ISSUE TITLE
EID Eddystone Ephemeral ID is 1 byte shorten

### ISSUE THREAD

**Issue by Zeruel92** [michaellee8/flutter_blue_beacon#1]
I'm using a bluetooth beacon with Eddystone EID and the ephemeralID result of 7 byte long instead of 8. Beacon is working with the producer app and google proximitybeaconApi.

I'm using the example code in this github. 

The byte missing are the last  (LSB) 

Example:
33646c167be8f2 ephemeral id from flutter_blue_beacon
33646c167be8f2c7 true ephemeral id

**Comment by michaellee8** [comment]
Maybe I made a bad decode, if you spot the place I made it wrong, can you kindly submit a PR for that?

**Comment by Zeruel92** [comment]
Sure i've done a pull request with a fix, i tested with some eddystone eid beacons and it works

**Comment by michaellee8** [comment]
Thank you so much
