### ISSUE TITLE
IBeacon Search fail on IOS (Iphone XS MAX)

### ISSUE THREAD

**Issue by c004245** [michaellee8/flutter_blue_beacon#2]
[✓] Flutter (Channel dev, v1.5.2, on Mac OS X 10.14.4 18E226, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

My flutter dart develop version.

and My phone IPhone XS MAX (ios12.2), Galaxy S8+ (Oreo)

I try test build this source

Galaxy S8+ is Ibeacon search normal work.
but XS Max always Search fail.

I check readme.txt 
`I have heard that iBeacon scans on iOS are not possible without using native APIs, if this is true, then iBeacon support for iOS in this library will be impossible since this library conducts low-level BLE scans and then translates it according to beacon protocols.`

As a result , is not available ibeacon on IOS?
thanks.

**Comment by michaellee8** [comment]
I thinks this plugin will not work on iOS. This plugin does works on raw Bluetooth data, which is intentionally blocked in iOS.

**Comment by c004245** [comment]
Ok, I think the same.

**Comment by surveshoeb** [comment]
Can you recommend any other plugin to scan on iOS?

**Comment by c004245** [comment]
@surveshoeb hello, Would you try it once?  https://pub.dev/packages/flutter_beacon
I think this source possible scan on iOS

**Comment by surveshoeb** [comment]
@c004245 Thanks.

**Comment by AdnanKazi** [comment]
> @surveshoeb hello, Would you try it once? https://pub.dev/packages/flutter_beacon
> I think this source possible scan on iOS

yes i have tried i works fine on IOS and Android

**Comment by michaellee8** [comment]
Consider this issue closed then, it seems that the alternative approach is as suggested above.
