### ISSUE TITLE
How to get 'Major' value

### ISSUE THREAD

**Issue by Calou07** [michaellee8/flutter_blue_beacon#3]
Hello, I am trying to get the Major value to use it in another function, but I don't manage to do it.

Can someone help me please ?

**Comment by michaellee8** [comment]
You mean `beacon.major`?

**Comment by Calou07** [comment]
Yes, I tried : `print('major: ${IBeacon().major}');`
but it returns "null" which means i don't have the scaned value.

**Comment by michaellee8** [comment]
IBeacon class is just an container of Beacon results, the scanning logic is not there, pls follow the examples in https://github.com/michaellee8/flutter_blue_beacon/blob/master/example/lib/main.dart

**Comment by Calou07** [comment]
I use the exact same code and I can see the true value in the app, it works fine.

My problem is that i can't put its value in a variable so i can une it elsewhere on the programe.

**Comment by michaellee8** [comment]
I cannot understand what are you talking about, can you provide some example code that reflect the problem?

**Comment by Calou07** [comment]
It's Okay, I solved my problem. 
Thank you for responding me and for your work.
