### ISSUE TITLE
Eddystone for ios

### ISSUE THREAD

**Issue by sailes-shakya** [michaellee8/flutter_blue_beacon#9]
I m not able search eddystone on ios .  is there any solution for that

**Comment by michaellee8** [comment]
Can you give more details on this? I didn't have an iOS device when I am developing this library so this library was not tested against iOS devices. However eddystone scanning on iOS should have be theoretically working.

**Comment by sailes-shakya** [comment]
m using beacon simulator on mobile while running the android ,,it is fine ,,but when i run ios the  scanResult.advertisementData.serviceData.keys is not coming same

**Comment by michaellee8** [comment]
can you post some code example on this? what is the output of
scanResult.advertisementData.serviceData.keys in both platforms? just
print() it and paste it here maybe?

**Comment by sailes-shakya** [comment]
m printing  
    print(scanResult.advertisementData.localName);
    print(scanResult.advertisementData.serviceData.keys);
    print(scanResult.advertisementData.serviceData.keys
        .contains("0000feaa-0000-1000-8000-00805f9b34fb"));

on ios :2021-06-18 22:09:31.857585+0545 Runner[15203:9587013] flutter:
2021-06-18 22:09:31.857692+0545 Runner[15203:9587013] flutter: A551641A-CA97-3275-D64A-4DD1CEEE195F
2021-06-18 22:09:31.857809+0545 Runner[15203:9587013] flutter:
2021-06-18 22:09:31.857967+0545 Runner[15203:9587013] flutter: (FEAA)

on android 👍
   localName: 
I/flutter (11030): manufacturerData: {}
I/flutter (11030): serviceData: {0000feaa-0000-1000-8000-00805f9b34fb: [48, 191, 75, 40, 214, 27, 226, 248, 19, 121, 0, 0, 0, 0]}

**Comment by sailes-shakya** [comment]
@michaellee8  thank you ur help i had solve the issue the service uuid should differetn on ios ,,the key is FEAA

**Comment by michaellee8** [comment]
> @michaellee8 thank you ur help i had solve the issue the service uuid should differetn on ios ,,the key is FEAA

Great, let's close this issue then
